(require 'org)
(defcustom org-latex-default-figure-position "b!"           "Default position for latex figures."        :group 'org-export-latex                   :type 'string)
(setq org-export-latex-hyperref-format "\\ref{%s}")

;; tools for CITATIONS
(org-add-link-type "cite"   (defun follow-cite (name)     "Open bibliography and jump to appropriate entry.        The document must contain ibliography{filename} somewhere        for this to work"       (find-file-other-window        (save-excursion          (beginning-of-buffer)          (save-match-data            (re-search-forward "\\\\bibliography{\\([^}]+\\)}")            (concat (match-string 1) ".bib"))))       (beginning-of-buffer)       (search-forward name))     (defun export-cite (path desc format)       "Export [[cite:cohen93]] as \cite{cohen93} in LaTeX."       (if (eq format 'latex)           (if (or (not desc) (equal 0 (search "cite:" desc)))               (format "\\cite{%s}" path)             (format "\\cite[%s]{%s}" desc path)))))
(org-add-link-type "citetext"   (defun follow-citetext (name)     "Open bibliography and jump to appropriate entry.        The document must contain ibliography{filename} somewhere        for this to work"       (find-file-other-window        (save-excursion          (beginning-of-buffer)          (save-match-data            (re-search-forward "\\\\bibliography{\\([^}]+\\)}")            (concat (match-string 1) ".bib"))))       (beginning-of-buffer)       (search-forward name))     (defun export-citetext (path desc format)       "Export [[citetext:cohen93]] as \citetext{cohen93} in LaTeX."       (if (eq format 'latex)           (if (or (not desc) (equal 0 (search "citetext:" desc)))               (format "\\citetext{%s}" path)             (format "\\citetext[%s]{%s}" desc path)))))
;;(setq org-latex-link-with-unknown-path-format "\\colorbox{green}{%s}")
(setq org-latex-link-with-unknown-path-format "\\textcolor{red}{\\emph{%s}}")
