#+TITLE: Heterogenous firing responses leads to diverse coupling to presynaptic activity in a simplified morphological model of layer V pyramidal neurons
#+AUTHOR: Y. Zerlaut^{1,2} \& A. Destexhe^{1,2}
#+INCLUDE: my_template.org 

* Abstract

  \bfseries

  Characterizing the input-output properties of neocortical neurons is
  of crucial importance to understand the properties emerging at the
  network level. In a companion communication [[(Zerlaut et al., 2016)]],
  we reported how individual neurons differ in their excitability and
  sensitivities to the properties of the membrane potential
  fluctuations. In the present report, we investigate how this
  heterogeneity is translated into diverse input-ouput properties 

  We study the coupling to different form of presynaptic activities,
  either balanced, unbalanced, proximal, distal, etc..

  In this letter, we investigate the 

\normalfont

* Introduction

[...]

* Results 
<<sec:results>>
\normalsize

** Building a 

#+ATTR_LATEX: :width \linewidth
#+NAME: fig:in-vitro-calib
#+CAPTION: *A theoretical framework for single cell computation.*
[[file:./figures/model_illustration.pdf]]

** Calibrating the morphological model on /in vitro/ measurements
<<sec:in-vitro-calib>>

#+ATTR_LATEX: :width \linewidth
#+NAME: fig:in-vitro-calib
#+CAPTION: *Calibrating the morphologically simplified model on /in vitro/ measurements: data Size variations in the theoretical model account for the heterogeneity in somatic input impedance measured /in vitro/* *(A)* Input impedance (left: modulus and right: phase shift) measured at the soma in intracellular recordings with sine-wave protocols. *(B)* Varying the size of the dendritic tree (length and diameter) partially accounts for the observed heterogeneity of the somatic input impedance.
[[file:./figures/calibration_on_input_imped.pdf]]

* Discussion

** An analytical model for dendritic integration in the fluctuation-driven regime

we provided a stratey for the analytical treatment of dendritic
integration in the fluctuation-driven regime that relies on 1)
shotnoise theory, 2) cable theory and 3) adequate approximations.

The main advantage of this model is that you can very naturall plug in
physiological parameters (because surface area is physiological as
well as transfer resistance to soma) and still it remains analytical.

** Heterogeneity of morpological and passive neuronal properties

In this study, the rescaling rule between input resistance at the soma
and the morphological model has led to the 

* Material and Methods 
\small

** Neuronal model: morphology
<<sec:correlation-generator>>

- morphology with symmetric branching

- E_e=0mV

** Compartementalization

 proximal vs. distal

various synaptic properties to obtain the location independence at the
soma [[cite:Macgee2000]].

** Correlation generator
<<sec:correlation-generator>>

Very simplistic model, synchrony is not shared across synapses. We
duplicate spikes of one synapse with probability $s$.

** Model equations: synaptic input and passive properties

The cable equation describes the temporal evolution and spatial spread of the membrane potential along the branches of the dendritic tree [[cite:RallXXXX]]:

\begin{equation}
\frac{1}{r_i} \frac{\partial^2 v}{\partial x^2} = i_m(v, x, t) = c_m \frac{\partial v}{\partial t} + \frac{v-E_L}{r_m} - i_{syn}(v,x,t)
\end{equation}

the membrane current $i_m(v, x, t)$ is a linear density of current (the presented cable equation already includes the radial symmetry). Though the modeled system has several branches, the equation can be written as a single spatial dependency $x$ because the symmetry of the model across branches imply that the properties of the input are identical at a given distance to the soma.

Synaptic input is modeled by local (infinitely small) and transient changes of membrane permeability to selective ionic channels. Both excitatory (accounting for AMPA synapses) and inhibitory synapses (accounting for GABAa synapses) are considered, their reversal potential is E_e=0mV and E_i=-80mV respectively. Each synaptic event is generated by a shotnoise and its effect on the conductance is a jump followed by an exponential decay. The form of the synaptic current is therefore:

\begin{equation}
\left\{
\begin{split}
& i_{syn}(v,x,t) = g_e(x,t)(E_e-v)+g_i(x,t)(E_i-v) \\
& g_e(x,t) = \sum_{\big\{x_e, \{t_e\} \big\}} \delta(x-x_e) \, \sum_{t_e \in \{t_e\}} Q_e(x) \, e^{-\frac{-(t-t_e)}{\tau_e(x)}} \, \mathcal{H}(t-t_e) \\
& g_i(x,t) = \sum_{\big\{x_i, \{t_i\} \big\}} \delta(x-x_i) \sum_{t_i \in \{t_i\}} Q_i(x) \, e^{-\frac{-(t-t_i)}{\tau_i(x)}} \, \mathcal{H}(t-t_i)\\
\end{split}
\right.
\end{equation}

where $g_e$ and $g_i$ are linear densities of conductances. Each
synapse, indexed by $s$, $s \in \{e,i\} $ has a position $x_s$ and a
set of presynaptic events $\{t_s\}$, hence the iteration over $
\big\{x_s, \{t_s\} \big\} $ for the sum over synapses for each
synaptic type. $\mathcal{H}$ is the Heaviside step function. The
presynaptic events $\{t_s\}$ are generated by point processes at fixed
frequencies $\nu_s$ with a given degree of synchrony, see details in
the previous section [[sec:correlation-generator]].

The model distinguishes two domains : a proximal domain with the upper
index $p$ and a distal domain with the upper index $d$ (see Figure
[[fig:model-illustration]]). Then the space-dependent quantities
(presynaptic frequencies, synaptic quantal and synaptic decay time
constant) can be written as :

#+NAME: eq:space-dep-quant
\begin{equation}
\left\{
\begin{split}
& \nu_e(x) = \nu_e^P + (\nu_e^d - \nu_e^p) \mathcal{H}(x-L_p)\\
&\nu_i(x) = \nu_i^P + (\nu_i^d - \nu_i^p) \mathcal{H}(x-L_p) \\
& Q_e(x) = Q_e^P + (Q_e^d - Q_e^p) \mathcal{H}(x-L_p)\\
& Q_i(x) = Q_i^P + (Q_i^d - Q_i^p) \mathcal{H}(x-L_p) \\
&\tau_e(x) = \tau_e^P + (\tau_e^d - \tau_e^p) \mathcal{H}(x-L_p)\\
&\tau_i(x) = \tau_i^P + (\tau_i^d - \tau_i^p) \mathcal{H}(x-L_p) 
\end{split}
\right.
\end{equation}


At the soma, $(x=0)$, we have a lumped impedance compartment. It has leaky RC circuit properties and also receives synaptic inhibition, the somatic membrane potential therefore follows :

\begin{equation}
\begin{split}
& C_M \frac{dV}{dt} + \frac{V-E_L}{R_M} + G_I(t) \, (V-E_i)  + I(t) = 0 \\
& G_i(t) = \sum_{N_i} \sum_{\{t_i\}} Q_i^p \, e^{-\frac{-(t-t_i)}{\tau_i^p}} \, \mathcal{H}(t-t_i)
\end{split}
\end{equation}

where $I(t)$ is the time-dependent input current from the soma into the dendrite. $R_M$ and $C_M$ are the RC properties of the lumped compartment (capital letters will indicate the somatic properties throughout the calculus). $N_i$ is the number of somatic synapses, each of them generates a point process $\{t_i\}$ of inhibitory synaptic events. The properties of the somatic synapses $(\nu_i^d, Q_i^d, \tau_i^d)$ are equivalent to the proximal ones.

This equation with the membrane potential continuity will determine the boundary condition at the soma (x=0). We identify $V(t)=v(0,t)$, then $I(t)$ is the current input into the dendritic tree at $x=0$ so it verifies:

\begin{equation}
\frac{\partial v}{\partial x}_{x=0} = - r_i \, I(t)
\end{equation}

So:
\begin{equation}
\frac{\partial v(x,t)}{\partial x}|_{x=0} = r_i \, 
\Big( C_M \frac{\partial v(0,t) }{\partial t} + \frac{v(0,t)-E_L}{R_m} + G_I(t) \, ( v(0,t)-E_i) \Big)
\end{equation}

Finally, the last boundary condition is that all branches terminate with an infinite resistance that impede current flow (sealed-end boundary conditions):

\begin{equation}
\frac{\partial v}{\partial x}_{x=L} = 0
\end{equation}

** Numerical implementation

The full model has been implemented numerically using the =NEURON=
software. The morphology

** Strategy for the analytical derivation

[[cite:Tuckwell2002]]

The full derivation has been conducted with the help of the python
modulus for symbolic computation: =sympy=. The resulting expression
were then exported to =numpy= functions for numerical evaluation. The
=ipython= notebook that presents the full derivation is available on
the following [[http://nbviewer.jupyter.org/urls/bitbucket.org/yzerlaut/diverse_coupling_to_synaptic_activity/raw/master/notebooks/Fluctuations_at_soma_for_Ball_&_Rall_tree.ipynb][link]].

** From fluctuation properties to spiking probability

Focus of a previous communication, see [[citet:Zerlaut2016]].

** Experimental preparation and electrophysiological recordings
<<sec:exp-prep>>

Experimental methods were identical to those presented in
[[citet:Zerlaut2016]]. Very briefly, we performed intracellular
patch-clamp recordings using the perforated patch technique on layer V
pyramidal neurons of coronal slices of juvenile mice primary visual
cortex. For the n=13 cells presented in this study, the access
resistance R_S was [[XX]] M\(\Omega\) \(\pm\) [[YY]], the leak current at
-75mV was [[XX]] pA \(\pm\) [[YY]], cells had an input resistance R_m of [[XX]]
M$\Omega$ \(\pm\) [[YY]] and a membrane time constant at rest of [[XX]] ms
\(\pm\) [[YY]].

** Input impedance characterization
<<sec:measured-quant>>

 To determine the input impedance at the soma, we injected sinusoidal
 currents in the current-clamp mode of the amplifier (Multiclamp 700B,
 Molecular Devices), we recorded the membrane potential response to a
 current input of the form \(I(t)=I \, \sin(2\pi \, f \, t) \), we
 varied the frequencies $f$ and amplitudes $I over 40 episodes per
 cell. The frequency range scanned was [0.1, 500] Hz. For each cell,
 we determined manually the current amplitude $I_0$ that gave a \sim
 5mV amplitude in a current step protocol, from this value, the value
 of $I$ was scaled exponentially between $I_0$ at 0.1 Hz and $50 I_0$
 at 500Hz. The reason for varying the current amplitude (and not only
 the oscillation frequency) in those input impedance protocols is to
 anticipate for the low pass filtering of the membrane and insure that
 the membrane potential response at high frequencies is far above the
 electronic noise level (\sim 0.1 mV).

After removing the first 3 periods of the oscillations (to avoid
transient effects), we fitted the membrane potential response to the
form:

\begin{equation}
V(t) = E_L + R \, I \, \sin(2\pi \, f \, t + \phi)
\end{equation}

where $E_L$, $R$ and $\phi$ were fitted with a least-square
minimization procedure. The frequency dependent values of $R$ and
$\phi$ give the modulus and phase shift of the input impedance
presented in Figure [[fig:in-vitro-calib]]A

** Numerical tools
<<sec:numerical-tools>>

All numerical simulations of single cell dynamics have been performed
with custom code written in the numerical library of =python=: =numpy=
and optimized with the =numba= library. For the neuronal model, each
point (a mean output frequency and its standard deviation across
trials) corresponds to numerical simulations running with a time step
dt=0.01ms, for a duration of 10s and repeated 4 times with different
seeds (one simulation duration: $\sim$ 2s of real time on a Dell
Optiplex 9020 desktop computer). Experimental protocols and
online-analysis have been written in =Elphy2=. Plots and data analysis
have been done thanks to the =SciPy= package.

** Acknowledgments
<<sec:acknowledgments>>

Y.Z was supported by fellowships from the Initiative d'Excellence
Paris-Saclay and the Fondation pour la Recherche Médicale (FDT
20150532751). Research funded by the CNRS, the ANR (Complex-V1
project) and the European Community (BrainScales FP7-269921 and the
Human Brain Project FP7-604102). The authors declare no competing
financial interests.

* References

\bibliography{tex/biblio}


