#+TITLE: Heterogenous firing responses leads to diverse coupling to presynaptic activity in a simplified morphological model of layer V pyramidal neurons
#+AUTHOR: Y. Zerlaut^{1,2} \& A. Destexhe^{1,2}
#+INCLUDE: my_template.org 

* Abstract

  \bfseries

  Characterizing the input-output properties of neocortical neurons is
  of crucial importance to understand the properties emerging at the
  network level. In a companion communication [[cite:Zerlaut2016]], we
  reported how individual neurons differ in their excitability and
  sensitivities to the properties of the membrane potential
  fluctuations. In the present report, we investigate how this
  heterogeneity is translated into diverse input-ouput properties
  (i.e. in th relation from presynaptic quantities to spiking
  probability).  

  To this purpose, we designed a simplified morphological model of
  layer V pyramidal neurons with a dendritic tree following Rall's
  branching rule. We first show that we are able to calibrate this
  simplified model on /in vitro/ measurements of somatic input
  impedance in layer V pyramidal neurons of juvenile mive visual
  cortex. We then propose and analytical derivation for the membrane
  potential fluctuations at the soma as a function of the properties
  of the synaptic bombardment.

  We study the coupling to different form of presynaptic activities,
  either balanced, unbalanced, proximal, distal, etc..

\normalfont

\newpage

* Introduction

[...]

Experimental evidence accumulate to show how the diverse activation of
neurons within a neocortical population might be the substrate of 

Though this diverse activation is likely to be due to specific
connectivity schemes, we explore here a complementary mechanism: given
the strong heterogeneity in electrophysiological properties of
neocortical pyramidal cells

\newpage

* Results 
<<sec:results>>
\normalsize

** A theoretical framework for single cell computation

[[taken from previous paper, to be adapted]]

Determining the cellular input-output functions is complex because
input of neocortical neurons are mostly in dendrites and output spikes
are generated in initial segments of an axon as reviewed in
[[citetext:Stuart2015]] and [[citetext:Debanne2011]] 
input will therefore crucially shape their input-output
relationship. Various parameters of presynaptic activity can
arbitrarily control the properties of the membrane potential
fluctuations at the soma. Those properties can be quantified by
identifying three somatic variables that provide a reduced description
of the dynamical state at the soma in the /fluctuation-driven/ regime:
the mean \mu_V, the standard deviation \sigma_V of the membrane
potential fluctuations and their typical autocorrelation time $\tau_V$
(see Methods[[sec:autocorrel-def]]). For example, the
excitatory/inhibitory balance controls the mean depolarization at the
soma \mu_V, the mean synaptic bombardment impacts the standard
deviation \sigma_V and the speed of the membrane potential
fluctuations \tau_V. Other effects such as synchrony in the
presynaptic spike trains or ratio between distally and proximally
targeting synaptic activity also affect the statistical properties of
the fluctuations. The effects of synaptic input and its dendritic
integration on somatic variables can be investigated theoretically
using cable theory [[cite:Tuckwell2002]] and will be the focus of a future
communication.

Because the spike initiation site lies electrotonically close to the
soma [[cite:Debanne2011]], we assume that those three purely somatic
variables will define the firing rate uniquely. In this study we
investigate the firing response in terms of those somatic variables
(illustrated in Figure [[fig:3D-motiv]]).

** A simplified morphological model of layer V pyramidal neurons

#+ATTR_LATEX: :width \linewidth
#+NAME: fig:model-illustration
#+CAPTION: *A theoretical framework for single cell computation.* *(A)* Paradigm of the study. To get the final input-output
[[file:./figures/model_illustration.pdf]]


\newpage 

** Calibrating the morphological model on /in vitro/ measurements
<<sec:in-vitro-calib>>

#+ATTR_LATEX: :width \linewidth
#+NAME: fig:in-vitro-calib
#+CAPTION: *Calibrating the model on /in vitro/ measurements: the simplified model and its size variations provides an approximation for the somatic input impedance and its heterogeneity*. *(A)* Input impedance (left: modulus and right: phase shift) measured at the soma in intracellular recordings with sine-wave protocols in current-clamp (inset). The color code indicates the input resistance and is likely to result from size variations of individual cells. *(B)* A medium size model accounts for the average data and varying the size of the dendritic tree and soma reproduces the trend in the individual measurements. Large cells (blue) have a lower modulus and a lower phase shift while small cells (red) have both a higher modulus and phase shift. *(C)* Left: We obtain a map between input resistance and size of the morphological model. Right: Representation of the medium-size model.
[[file:./figures/calibration_on_input_imped.pdf]]


\newpage

** An analytical approximation for the properties of the membrane potential fluctuations at the soma

Needed because simulations of morphologies are computationally very
expensive, very limited scan of input space is allowed.

comparison between analytical approx and simulations in =NEURON=

#+ATTR_LATEX: :width \linewidth
#+NAME: fig:analytics-accuracy
#+CAPTION: *Accuracy of the analytical approximation for the properties of the membrane potential fluctuations: comparison between numerical simulations and analytical estimates*. We vary 
[[./figures/none_yet.pdf]]

We emphasize here that even if the analytical description uses the
reduction to the equivalent cylinder (and therefore could be seen as
equivalent to the Ball and Stick model), the described model has
separate branches so that the fluctuations are uncorrelated from
branches to branches unlike in the Ball and Stick model.

** Fluctuations properties for various type of synaptic activities



#+ATTR_LATEX: :width \linewidth
#+NAME: fig:analytics-accuracy
   #+CAPTION: *Fluctuations properties as a function of the population activity for various properties of synaptic activty*. *(A)* We vary 
[[./figures/none_yet.pdf]]

** Heterogeneous firing response induce diverse coupling to the types of synaptic activity

* Discussion

** An analytical model for dendritic integration in the fluctuation-driven regime

we provided a stratey for the analytical treatment of dendritic
integration in the fluctuation-driven regime that relies on 1)
shotnoise theory, 2) cable theory and 3) adequate approximations.

The main advantage of this model is that you can very naturall plug in
physiological parameters (because surface area is physiological as
well as transfer resistance to soma) and still it remains analytical.

Literature suffers from the reduction to single-compartment

The current model provides a tool to make network dynamics question
amenable to mathematical analysis with morphologically detailed
models.

** Heterogeneity of morpological and passive neuronal properties

In this study, the rescaling rule between input resistance at the soma
and the morphological model has led to a relative 

** Diverse coupling to presynaptic activity

* Material and Methods 
\small

** Neuronal model
<<sec:correlation-generator>>

The model is illustrated on Figure [[fig:model-illustration]]B.

- morphology with symmetric branching

- different properties for the proximal part vs the distal part 

** Compartementalization

 proximal vs. distal

various synaptic properties to obtain the location independence at the
soma [[cite:Macgee2000]].

** Correlation generator
<<sec:correlation-generator>>

Very simplistic model, synchrony is not shared across synapses. We
duplicate spikes of one synapse with probability $s$.

** Model equations: synaptic input and passive properties

The cable equation describes the temporal evolution and spatial spread of the membrane potential along the branches of the dendritic tree [[cite:RallXXXX]]:

\begin{equation}
\frac{1}{r_i} \frac{\partial^2 v}{\partial x^2} = i_m(v, x, t) = c_m \frac{\partial v}{\partial t} + \frac{v-E_L}{r_m} - i_{syn}(v,x,t)
\end{equation}

the membrane current $i_m(v, x, t)$ is a linear density of current (the presented cable equation already includes the radial symmetry). Though the modeled system has several branches, the equation can be written as a single spatial dependency $x$ because the symmetry of the model across branches imply that the properties of the input are identical at a given distance to the soma.

Synaptic input is modeled by local (infinitely small) and transient changes of membrane permeability to selective ionic channels. Both excitatory (accounting for AMPA synapses) and inhibitory synapses (accounting for GABAa synapses) are considered, their reversal potential is E_e=0mV and E_i=-80mV respectively. Each synaptic event is generated by a shotnoise and its effect on the conductance is a jump followed by an exponential decay. The form of the synaptic current is therefore:

\begin{equation}
\left\{
\begin{split}
& i_{syn}(v,x,t) = g_e(x,t)(E_e-v)+g_i(x,t)(E_i-v) \\
& g_e(x,t) = \sum_{\big\{x_e, \{t_e\} \big\}} \delta(x-x_e) \, \sum_{t_e \in \{t_e\}} Q_e(x) \, e^{-\frac{-(t-t_e)}{\tau_e(x)}} \, \mathcal{H}(t-t_e) \\
& g_i(x,t) = \sum_{\big\{x_i, \{t_i\} \big\}} \delta(x-x_i) \sum_{t_i \in \{t_i\}} Q_i(x) \, e^{-\frac{-(t-t_i)}{\tau_i(x)}} \, \mathcal{H}(t-t_i)\\
\end{split}
\right.
\end{equation}

where $g_e$ and $g_i$ are linear densities of conductances. Each
synapse, indexed by $s$, $s \in \{e,i\} $ has a position $x_s$ and a
set of presynaptic events $\{t_s\}$, hence the iteration over $
\big\{x_s, \{t_s\} \big\} $ for the sum over synapses for each
synaptic type. $\mathcal{H}$ is the Heaviside step function. The
presynaptic events $\{t_s\}$ are generated by point processes at fixed
frequencies $\nu_s$ with a given degree of synchrony, see details in
the previous section[[sec:correlation-generator]].

The model distinguishes two domains : a proximal domain with the upper
index $p$ and a distal domain with the upper index $d$ (see Figure
[[fig:model-illustration]]). Then the space-dependent quantities
(presynaptic frequencies, synaptic quantal and synaptic decay time
constant) can be written as :

#+NAME: eq:space-dep-quant
\begin{equation}
\left\{
\begin{split}
& \nu_e(x) = \nu_e^P + (\nu_e^d - \nu_e^p) \mathcal{H}(x-L_p)\\
&\nu_i(x) = \nu_i^P + (\nu_i^d - \nu_i^p) \mathcal{H}(x-L_p) \\
& Q_e(x) = Q_e^P + (Q_e^d - Q_e^p) \mathcal{H}(x-L_p)\\
& Q_i(x) = Q_i^P + (Q_i^d - Q_i^p) \mathcal{H}(x-L_p) \\
&\tau_e(x) = \tau_e^P + (\tau_e^d - \tau_e^p) \mathcal{H}(x-L_p)\\
&\tau_i(x) = \tau_i^P + (\tau_i^d - \tau_i^p) \mathcal{H}(x-L_p) 
\end{split}
\right.
\end{equation}


At the soma, $(x=0)$, we have a lumped impedance compartment. It has leaky RC circuit properties and also receives synaptic inhibition, the somatic membrane potential therefore follows :

\begin{equation}
\begin{split}
& C_M \frac{dV}{dt} + \frac{V-E_L}{R_M} + G_I(t) \, (V-E_i)  + I(t) = 0 \\
& G_i(t) = \sum_{N_i} \sum_{\{t_i\}} Q_i^p \, e^{-\frac{-(t-t_i)}{\tau_i^p}} \, \mathcal{H}(t-t_i)
\end{split}
\end{equation}

where $I(t)$ is the time-dependent input current from the soma into the dendrite. $R_M$ and $C_M$ are the RC properties of the lumped compartment (capital letters will indicate the somatic properties throughout the calculus). $N_i$ is the number of somatic synapses, each of them generates a point process $\{t_i\}$ of inhibitory synaptic events. The properties of the somatic synapses $(\nu_i^d, Q_i^d, \tau_i^d)$ are equivalent to the proximal ones.

This equation with the membrane potential continuity will determine the boundary condition at the soma (x=0). We identify $V(t)=v(0,t)$, then $I(t)$ is the current input into the dendritic tree at $x=0$ so it verifies:

\begin{equation}
\frac{\partial v}{\partial x}_{x=0} = - r_i \, I(t)
\end{equation}

So:
\begin{equation}
\frac{\partial v(x,t)}{\partial x}|_{x=0} = r_i \, 
\Big( C_M \frac{\partial v(0,t) }{\partial t} + \frac{v(0,t)-E_L}{R_m} + G_I(t) \, ( v(0,t)-E_i) \Big)
\end{equation}

Finally, the last boundary condition is that all branches terminate with an infinite resistance that impede current flow (sealed-end boundary conditions):

\begin{equation}
\frac{\partial v}{\partial x}_{x=L} = 0
\end{equation}

** Numerical implementation

The full model has been implemented numerically using the =NEURON=
software. The morphology

** Strategy for the analytical derivation

# Strategy for the analytical derivation

We present here a derivation that provides an analytical approximation
for the properties of the fluctuations of the membrane potential at
the soma for our model. Summing up its properties, we get: 1) a
morphology with a lumped somatic compartement and a dendritic tree of
symmetric branching following Rall's rule 2) conductance-based
synapses 3) independent excitatory and inhibitory shotnoise input
spread all over the morphology 4) assymetric properties between a
proximal part and a distal part and 5) a certain degree of synchrony
in the pre-synaptic spikes.

The properties of the membrane potential fluctuations at the soma
correspond to three stationary statistical properties of the
fluctuations: their mean $\mu_V$, their standard deviation
\(\sigma_V\) and their /global/ autocorrelation time
\(\tau_V\). Following [[citetext:Zerlaut2016]], we emphasize that the
/global/ autocorrelation time is a partial description of the
autocorrelation function (as the autocorrelation function is not
exponential) but it constitues the first order description of the
temporal dynamics of the fluctuations.

A commonly adopted strategy in the /fluctuation-driven/ regime to
obtain statistical properties is to use stochastic calculus after
having performed the /diffusion approximation/, i.e. approximating the
synaptic conductance time course by a stochastic process, see
e.g. [[cite:Tuckwell2002]]). This approach is nonetheless not easily
generalizable to conductance input in an extended structure and render
the inclusion of assymetric properties (proximal vs distal)
complicated. We rather propose here an approach that combines
simplifying assumptions and results from shotnoise theory, it
constitues an extension of the approach proposed in [[citetext:Kuhn2004]].

The strategy is the following, for each set of synaptic stimulation
\(\{\nu^e_p, \nu_i^p, \nu_e^d, \nu_i^d, s\}\): 1) we derive a mean
membrane potential \(\mu_V(x)\) corresponding to the stationary
response to constant densities of conductances given by the means of
the synaptic stimulation. We use this space-dependent membrane
potential \(\mu_V(x)\) to fix the driving force all along the membrane
for all synapses, 2) the relation between synaptic events and the
membrane potential is now linear, we calculate the effect of a given


We use the reduction to the equivalent cylinder

- 3) The relation between synaptic events and the membrane potential
  is now linear


We will split the cable into two domains $[0,L_P]$ and $[L_p,L]$, in each of the domain, we can apply the previous strategy because the mean conductance is constant and at the junction between the two cables, we have two condtions, the continuity of the membrane potential : 
$$
v(x \rightarrow L_p^-)=v(x \rightarrow L_p^+)
$$
and the conservation of the current
$$
\frac{1}{r_i} \frac{\partial v^p}{\partial x}_{x \rightarrow L_p^-} = 
\frac{1}{r_i} \frac{\partial v^d}{\partial x}_{x \rightarrow L_p^+} 
$$

where the notation : $x \rightarrow y^-$ and $x \rightarrow y^+$ account for the limit toward $y$ coming from lower or higher values respecively.


The full derivation has been conducted with the help of the python
modulus for symbolic computation: =sympy=. The resulting expression
were then exported to =numpy= functions for numerical evaluation. The
=ipython= notebook that presents the full derivation is available on
the following [[http://nbviewer.jupyter.org/urls/bitbucket.org/yzerlaut/diverse_coupling_to_synaptic_activity/raw/master/notebooks/Fluctuations_at_soma_for_Ball_&_Rall_tree.ipynb][link]].

** From fluctuation properties to spiking probability


Focus of a previous communication, see [[citetext:Zerlaut2016]].

** Experimental preparation and electrophysiological recordings
<<sec:exp-prep>>

Experimental methods were identical to those presented in
[[citetext:Zerlaut2016]]. Very briefly, we performed intracellular
patch-clamp recordings using the perforated patch technique on layer V
pyramidal neurons of coronal slices of juvenile mice primary visual
cortex. For the n=13 cells presented in this study, the access
resistance R_S was [[XX]] M\(\Omega\) \(\pm\) [[YY]], the leak current at
-75mV was [[XX]] pA \(\pm\) [[YY]], cells had an input resistance R_m of [[XX]]
M$\Omega$ \(\pm\) [[YY]] and a membrane time constant at rest of [[XX]] ms
\(\pm\) [[YY]].

** Input impedance characterization
<<sec:measured-quant>>

 To determine the input impedance at the soma, we injected sinusoidal
 currents in the current-clamp mode of the amplifier (Multiclamp 700B,
 Molecular Devices), we recorded the membrane potential response to a
 current input of the form \(I(t)=I \, \sin(2\pi \, f \, t) \), we
 varied the frequencies $f$ and amplitudes $I over 40 episodes per
 cell. The frequency range scanned was [0.1, 500] Hz. For each cell,
 we determined manually the current amplitude $I_0$ that gave a \sim
 5mV amplitude in a current step protocol, from this value, the value
 of $I$ was scaled exponentially between $I_0$ at 0.1 Hz and $50 I_0$
 at 500Hz. The reason for varying the current amplitude (and not only
 the oscillation frequency) in those input impedance protocols is to
 anticipate for the low pass filtering of the membrane and insure that
 the membrane potential response at high frequencies is far above the
 electronic noise level (\sim 0.1 mV).

After removing the first 3 periods of the oscillations (to avoid
transient effects), we fitted the membrane potential response to the
form:

\begin{equation}
V(t) = E_L + R \, I \, \sin(2\pi \, f \, t - \phi)
\end{equation}

where $E_L$, $R$ and $\phi$ were fitted with a least-square
minimization procedure. The frequency dependent values of $R$ and
$\phi$ give the modulus and phase shift of the input impedance
presented in Figure [[fig:in-vitro-calib]]A

** Numerical tools
<<sec:numerical-tools>>

All numerical simulations of single cell dynamics have been performed
with custom code written in the numerical library of =python=: =numpy=
and optimized with the =numba= library. For the neuronal model, each
point (a mean output frequency and its standard deviation across
trials) corresponds to numerical simulations running with a time step
dt=0.01ms, for a duration of 10s and repeated 4 times with different
seeds (one simulation duration: $\sim$ 2s of real time on a Dell
Optiplex 9020 desktop computer). Experimental protocols and
online-analysis have been written in =Elphy2=. Plots and data analysis
have been done thanks to the =SciPy= package.

** Acknowledgments
<<sec:acknowledgments>>

Y.Z was supported by fellowships from the Initiative d'Excellence
Paris-Saclay and the Fondation pour la Recherche Médicale (FDT
20150532751). Research funded by the CNRS, the ANR (Complex-V1
project) and the European Community (BrainScales FP7-269921 and the
Human Brain Project FP7-604102). The authors declare no competing
financial interests.

* References

\bibliography{tex/biblio}


