#+TITLE: Heterogenous firing responses leads to diverse coupling to presynaptic activity in a simplified  morphological model of layer V pyramidal neurons
#+AUTHOR: Y. Zerlaut^{1,2} \& A. Destexhe^{1,2}
#+INCLUDE: my_template.org 

* Abstract

  \bfseries 

  Biological systems display heterogeneity

  In a recent report, we quantified this heterogneity in the fluct. driven regime

  We study the coupling to different form of presynaptic activities,
  either balanced, unbalanced, proximal, distal, etc..

  In this letter, we investigate the 

\normalfont


* Introduction

[...]


* Results 
<<sec:results>>

** Morphology calibration on /in vitro/ data
<<sec:in-vitro-calib>>

#+ATTR_LATEX: :float c :width 1.2\linewidth
#+NAME: fig:in-vitro-calib
#+CAPTION: *Size variations in the theoretical model account for the heterogeneity in somatic input impedance measured /in vitro/* *(A)* Input impedance (left: modulus and right: phase shift) measured at the soma in intracellular recordings with sine-wave protocols. *(B)* Varying the size of the dendritic tree (length and diameter) partially accounts for the observed heterogeneity of the somatic input impedance.
[[file:./figures/calibr_on_input_imped.pdf]]


* Discussion


* Material and Methods 
\small

** Experimental preparation
<<sec:exp-prep>>

Experimental procedures with animals were performed following the
instructions of the European Council Directive 2010 86/609/EEC and its
French transposition (Décret 2013/118). Swiss wild-type mice of either
sex, 8–13 days old, were anesthetized with inhaled isoflurane and
decapitated, their brain was rapidly removed and immersed in cold
“cutting” solution (\sim 4^{o}C) containing the following (in mM): 110
Choline Chloride, 2.5 KCl, 1.25 NaH2PO4, 26 NaHCO3, 8 MgCl2, 1 CaCl2,
10 glucose, pH equilibrated to 7.3 with O2/CO2 (95\%/5\%). Coronal
slices (300 $\mu\mathrm{m}$ thick) were prepared with a vibratome
(Leica VT1200 S, Leica Microsystems) and stored at room temperature in
oxygenated aCSF containing the following (in mM): 126 NaCl, 2.5 KCl,
1.5 NaH2PO4, 26 NaHCO3, 2 MgCl2, 2 CaCl2 and 10 glucose, pH 7.4. The
slices were then transferred to the recording chamber (perfused with
the same solution) where the temperature was maintained at
34^{o}C. Slices containing primary visual cortex were taken as the
first four slices containing brain cortex starting from the most
caudal one.


** Electrophysiological recordings
<<sec:electrophy>>

We performed intracellular recordings of visually identified pyramidal
cells located in the layer V of mice cortex using the perforated patch
technique.

Patch electrodes (tip resistance: 1.5–2.5 $\mathrm{M}\Omega$) were
pulled on a Sutter P-1000 apparatus (Sutter Instruments) and filled in
a two step procedure. The pipettes were pre-filled with a solution
containing the following (in mM): 130 K-Gluconate, KCl 7, NaCl 1,
MgCl2 4, HEPES 10, pH adjusted to 7.3 with KOH (osmolarity 260
mOsm). The pipette was then back-filled with the same solution to
which was added Amphotericin-B (Sigma Aldrich) previously dissolved in
DMSO, the final concentration of Amphotericin-B was 60
$\mu\mathrm{M}$. The reason for this two step procedure is to allow a
current flow out of the pipette (to preserve the tip from dirt)
without pouring the perforant onto the target cell during the pipette
approach. The perforation could therefore happen only after diffusion
of Amphotericin-B through the "clean" solution, this usually took 5-10
minutes after the pipette filling, thus allowing the cell-attached
configuration to form in absence of the perforant molecule.

We recorded from n=30 cells. After perforation, the access resistance
R_S was 14.7M\(\Omega\) \(\pm\) 6.9. This value was plugged in into
the amplifier-build bridge compensation system during the
current-clamp recordings. At -75 mV, the recordings exhibited a leak
current of -31.9 pA \(\pm\) 26.8 (minimum observed resting potential:
-76 mV), this current value was then set for each neuron as the
holding current during the recording. Recorded pyramidal cells had an
input resistance R_m of 355.9 M$\Omega$ \(\pm\)184.1 and a membrane
time constant at rest of : 31.4ms \(\pm\) 12.0. Recordings lasted 36.7
min \pm 20.9. In the absence of current injection, cells presented a
quiescent activity.

The liquid junction potential was measured to be 6 mV and membrane
potential recordings were corrected accordingly. Note that there might
be anyway an unknown constant shift in the voltage value because the
Amphotericin-B pores are selective channels (so that a non-zero
reversal potential could appear if the cellular medium and our pipette
medium are different). The absolute values of the membrane potential
presented here should therefore be interpreted carefully (but this
would only affect the \( \langle V_\mathrm{thre}^\mathrm{eff}
\rangle_\mathcal{D} \) quantity reported in this study).



** Measuring firing rate
<<sec:measured-quant>>

 We measured the firing rate simply by counting spikes over a fixed
 time window. Spikes were detected as a upward crossings of -20mV. The
 first 100ms we removed to avoid transient effects associated to the
 membrane potential rise. The duration of the stimulation was usually
 5s, therefore the minimum (non zero) rate was 0.2 Hz. Also an online
 analysis was counting spikes and the stimulation was stopped when
 \sim 20 spikes were reached (see in Figure [[fig:exp-charact]]E, the
 middle episode is shorter than the two other ones), this to avoid
 spending to much recording time in the high firing rate range.


** Dynamic-clamp
<<sec:dynamic-clamp>>

Our dynamic-clamp system consists of an Intel Quad-Core computer
equipped with an acquisition card (NI PCI-6251 ADC/DAC,Mseries,
National Instruments) connected to the amplifier operating in
current-clamp mode. The dynamic-clamp software is based on a custom
ADC/DAC (analog-to-digital/digital-to-analog) program used for data
acquisition and analysis [Elphy2, developed at Unité de Neurosciences,
Information et Complexité (UNIC) by Gérard Sadoc] and interfaced with
the =NEURON= simulator version 6.0 (Hines and Carnevale,
1997). =NEURON= was modified and recompiled to run under the INtime
(TenAsys), a Real Time Operating System running alongside Microsoft
Windows.  The recordings were performed using a Multiclamp 700B
amplifier (Molecular Devices). Stimulation protocols were run in real
time with the acquisition card at 10 kHz. Acquisition and filter
frequencies were set at 10 and 4 kHz, respectively. An unfiltered copy
of the membrane potential signal was feeding the /dynamic clamp/
system.


** Single compartment approximation
<<sec:single-comp>>

Both for the experimentally recorded neurons and for the theoretical
models, we will use the single compartment membrane equation. The
passive properties of a neuron are therefore described by a leak
conductance g_L, a capacitance C_m and a resting potential E_L. With
an additional current $I(V, t)$, the membrane potential thus follows:

#+NAME: eq:membrane-eq
\begin{equation}
  C_\mathrm{m} \frac{dV}{dt} = I(V, t) + g_\mathrm{L} \, (E_\mathrm{L} - V)
\end{equation}

Passive properties were fitted from the response to a hyperpolarizing
current step for the recorded neocortical neurons in the subthreshold
domain (around -75 \pm 5mV).

Though this approximation was found to be satisfactory (Figure
[[fig:exp-charact]]C), monitoring possible deviations is important in this
study as the approximation is used to shape the fluctuations of the
membrane potential. We therefore performed a cell-by-cell
quantification of the accuracy of the approximation as follows. We
take the protocols that were used to determine the membrane
properties: prior to each protocol, we recorded and averaged the
response to 10 current pulses of $\sim$ 500ms and of $\Delta I \sim$
15pA amplitude, not the (noisy) continuous monitoring presented in
Figure [[fig:exp-charact]]. We average over trials the membrane potential
response and fit an exponential curve to this mean response
$V_\mathrm{sc}^\mathrm{fit}(t)$, we get a membrane time
$\tau_\mathrm{m}^0$ and a membrane resistance $R_\mathrm{m}^0$. We
define the residual trace as the normalized absolute difference
between the fit and the trace :

\begin{equation}
\mathrm{Res}(t) = \big| \frac{  V(t) - V_\mathrm{sc}^\mathrm{fit}(t)}{R_m^0 \Delta I}  \big| 
\label{eq:residual-single-comp}
\end{equation}

 Now we quantify the accuracy of the single-compartment approximation
 by taking the (normalized) integral over 7 membrane time constant of
 the residual trace.
 # (see bottom traces in [[fig:single-comp-approx]]B and [[fig:single-comp-approx]]C).

\begin{equation}
C_\mathrm{sc} = \int_{t_0}^{t_0+7 \, \tau_m^0} \frac{dt}{7\,\tau_m^0}
\mathrm{Res}(t)
\label{eq:accuracy-coeff-single-comp}
\end{equation}

 The two normalizations (by membrane resistance and membrane time
 constant) were performed to yield comparable quantities for different
 membrane parameters.

 We investigated whether the quality of the approximation had an
 impact on the excitability and sensitivities presented in the
 Results, we found no significant correlations between those
 quantities and the quality of the recordings (c<0.2 and p>0.2 for all
 characteristics, Pearson correlations), thus suggesting that the
 results of our study were not impacted by deviations from the single
 compartment approximation.


** Global autocorrelation time
<<sec:autocorrel-def>>

We present here a theoretical estimate for the speed of the membrane
potential fluctuations.

In the case of a fluctuating synaptic input with temporal dynamics
(e.g. resulting from a shotnoise of /exponential/ synapses considered
in this study, unlike the /delta/ synapses considered in other
studies, see [[citetext:Amit1997]] for an example), the autocorrelation
function is not an exponential function. Consequently, the resulting
membrane fluctuations can not be characterised by a single time
constant $\tau_V$ (see the inset in Figure
[[fig:3D-motiv]]). Nevertheless, the time constant taken from an
exponential approximation of the normalized autocorrelation function
corresponds to a first order description of the autocorrelation and
will be the main contributor to the temporal dynamics of the
fluctuations.

As a theoretical prediction for this /global autocorrelation/ time, we
take the half integral of the normalized autocorrelation correlation
function:

#+NAME: eq:Tv-def
\begin{equation}
  \tau_V = \frac{1}{2} \, \int_\mathbb{R} d \tau \frac{A(\tau)}{A(0)}
\end{equation}

where \( A(\tau) \) is the autocorrelation function of the V_m
fluctuations (see an example of \( A(\tau)/A(0) \) in Figure
[[fig:3D-motiv]]). From shotnoise theory [[cite:Daley2007]], we will obtain
the power spectral density of the V_m fluctuations \( P_V(f) \), so we
re-express the global autocorrelation time as:

#+NAME: eq:Tv-def-with-pwd
\begin{equation}
  \tau_V = \frac{1}{2} \, \big( \frac{\int_\mathbb{R} P_V(f) \, d f}{ P_V(0) } \big)^{-1}
\end{equation}

 In this study, this formula reduces to a very simple form (see next
 section). Note that the relations presented in this paper rely on the
 following convention for the Fourier transform: \( \hat{F}(f) =
 \int_\mathbb{R} F(t) \, e^{- 2 i \pi f t} \, dt\).


** Numerical tools
<<sec:numerical-tools>>

All numerical simulations of single cell dynamics have been performed
with custom code written in the numerical library of =python=: =numpy=
and optimized with the =numba= library. For the neuronal model, each
point (a mean output frequency and its standard deviation across
trials) corresponds to numerical simulations running with a time step
dt=0.01ms, for a duration of 10s and repeated 4 times with different
seeds (one simulation duration: $\sim$ 2s of real time on a Dell
Optiplex 9020 desktop computer). Experimental protocols and
online-analysis have been written in =Elphy2=. Plots and data analysis
have been done thanks to the =SciPy= package.


** Acknowledgments  :noexport:
<<sec:acknowledgments>>


We would like to acknowledge the contribution of Gérard Sadoc in
helping us to design the dynamic-clamp protocols. We also thank
Guillaume Hucher for the histological work as well as Manon Richard
and Aurélie Daret for animal facilities. Y.Z was supported by
fellowships from the Initiative d'Excellence Paris-Saclay and the
Fondation pour la Recherche Médicale (FDT 20150532751). Research
funded by the CNRS, the ANR (Complex-V1 project) and the European
Community (BrainScales FP7-269921 and the Human Brain Project
FP7-604102). The authors declare no competing financial interests.



* References

\bibliography{tex/biblio}


