#+TITLE: Supplementary Material \\ \large{Heterogenous firing responses leads to diverse coupling to presynaptic activity in a simplified morphological model of layer V pyramidal neurons}
#+AUTHOR: Y. Zerlaut^1 \& A. Destexhe^1
#+INCLUDE: supp.org 

\newpage

* Reduction to the equivalent cylinder
<<sec:reduction-to-eq-cyl>>

The key of the derivation relies on having the possibility to reduce
the complex morphology to an equivalent cylinder [[cite:Rall1962]]. We
adapted this procedure to capture the change in integrative properties
of the membrane that results from the mean synaptic bombardment during
active cortical states, reviewed in [[citetext:Destexhe2003]].

For a set of synaptic stimulation \(\{\nu^e_p, \nu_i^p, \nu_e^d,
\nu_i^d, s\}\), let's introduce the following stationary densities of
conductances:

\begin{equation}
\left\{
\begin{split}
& g_{e0}^p = \pi \, d \, \mathcal{D}_e \, \nu_e^p \, \tau_e^p \, Q_e^p \quad ;  \quad
g_{i0}^p = \pi \, d \, \mathcal{D}_i \, \nu_i^p \, \tau_i^p \, Q_i^p \\
& g_{e0}^d = \pi \, d \, \mathcal{D}_e  \, \nu_e^d \, \tau_e^d \, Q_e^d \quad ; \quad 
g_{i0}^d = \pi \, d \, \mathcal{D}_i \, \nu_i^d \, \tau_i^d \, Q_i^d
\end{split}
\right.
\end{equation}

where $\mathcal{D}_e$ and $\mathcal{D}_i$ are the excitatory and
inhibitory synaptic densities (see Figure [[fig:model-illustration]]B).

We introduce two activity-dependent electrotonic constants relative to
the proximal and distal part respectively:

\begin{equation}
\lambda^p= \sqrt{\frac{r_m}{r_i (1 + r_m g_{e0}^p + r_m g_{i0}^p)}}
\quad 
\lambda^d= \sqrt{\frac{r_m}{r_i (1 + r_m g_{e0}^d + r_m g_{i0}^d)}}$
\end{equation}

For a dendritic tree of total length $l$, whose proximal part ends at
$l_p$ and with $B$ evenly spaced generations of branches, we define
the space-dependent electrotonic constant:

\begin{equation}
 \lambda(x) = \big( \lambda^p + \mathcal{H}(x-l_p)(\lambda^d-\lambda^p) \big)
 2^{- \frac{1}{3} \, \lfloor \frac{B \, x}{l} \rfloor}
\end{equation}

where \( \lfloor . \rfloor \) is the floor function. Note that
$\lambda(x)$ is constant on a given generation, but it decreases from
generation to generation because of the decreasing diameter along the
dendritic tree. It also depends on the synaptic activity and
therefore has a discontinuity at $x=l_p$.

Following [[citetext:Rall1962]], we now define a dimensionless length $X$:

#+NAME: eq:x-rescale
\begin{equation}
 X(x) = \int_0^x \frac{dx}{\lambda(x)}
\end{equation}

We define \(L= X(l) \) and \(L_p= X(l_p) \), the total length and
proximal part length respectively (capital letters design rescaled
quantities).

* Mean membrane potential
<<sec:mean-derivation>>

We derive the mean membrane potential \(\mu_V(x)\) corresponding to
the stationary response to constant densities of conductances given by
the means of the synaptic stimulation. We obtain the stationary
equations by removing temporal derivatives in Equation, the set of
equation governing this mean membrane potential in all branches is
therefore:

#+NAME: eq:model-equation-muV
\begin{equation}
\left\{
\begin{split}
& \frac{1}{r_i} \frac{\partial^2 \mu_v}{\partial x^2} = \frac{\mu_v(x)-E_L}{r_m} \\
& \qquad - g_{e0}^p \, (\mu_v(x) - E_e) - g_{0i}^p \, (\mu_v(x) - E_i) \quad \forall x \in [0,l_p] \\
& \frac{1}{r_i} \frac{\partial^2 \mu_v}{\partial x^2} =  \frac{\mu_v(x)-E_L}{r_m} \\
& \qquad - g_{e0}^d \, (\mu_v(x) - E_e) - g_{0i}^d \, (\mu_v(x) - E_i)  \quad \forall x \in [l_p,l]  \\
& \frac{\partial \mu_v}{\partial x}_{|x=0} = r_i \, \big(
 \frac{\mu_v(0)-E_L}{R_m} + G_{i0}^S \, ( \mu_v(0)-E_i) \big)\\
& \mu_v(l_p^-,t) = \mu_v(l_p^+,t) \\
& \frac{\partial \mu_v}{\partial x}_{l_p^-} 
= \frac{\partial \mu_v}{\partial x}_{l_p^+} \\
& \frac{\partial \mu_v}{\partial x}_{x=l} = 0
\end{split}
\right.
\end{equation}

Because the reduction to the equivalent cylinder conserves the
membrane area and the previous equation only depends on density of
currents, the equation governing $\mu_v(x)$ in all branches can be
transformed into an equation on an equivalent cylinder of length $L$.
We rescale $x$ by $\lambda(x)$ (see Equation [[eq:x-rescale]]) and we
obtain the equation verified by \(\mu_V(X)\):

#+NAME: eq:model-equation-muV-rescaled
\begin{equation}
\left\{
\begin{split}
& \frac{\partial^2 \mu_v}{\partial X^2} = \mu_v(X)-v_0^p \quad \forall X \in [0,L_p] \\
&\frac{\partial^2 \mu_v}{\partial X^2} = \mu_v(X)-v_0^d \quad \forall X \in [L_p,L]  \\
&\frac{\partial \mu_v}{\partial X}|_{X=0} = \gamma^p \, 
\Big( \mu_v(0) - V_0  \Big) \\
&\mu_v(L_p^-) = \mu_v(L_p^+) \\
&\frac{\partial \mu_v}{\partial X}_{L_p^-} = \frac{\lambda^p}{\lambda^d}
\frac{\partial \mu_v}{\partial X}_{L_p^+} \\
&\frac{\partial \mu_v}{\partial X}_{X=L} = 0 
\end{split}
\right.
\end{equation}

where:

\begin{equation}
\begin{split}
& v_0^p = \frac{E_L + r_m g_{e0}^p E_e + r_m g_{i0}^p E_i}{ 1 + r_m g_{e0}^p + r_m g_{i0}^p }\\
& v_0^d = \frac{E_L + r_m g_{e0}^d E_e + r_m g_{i0}^d E_i}{ 1 + r_m g_{e0}^d + r_m g_{i0}^d }\\
& \gamma^p = \frac{r_i \lambda^p \, (1+ G_i^0 R_m)}{R_m}\\
& V_0 = \frac{E_L + G_i^0 R_m E_i}{ 1 +  + G_i^0 R_m }
\end{split}
\end{equation}

The solution for this equation is:
\begin{equation}
 \mu_v(X) = 
\left\{
\begin{split}
v_0^p + A &\cosh(X) + (v_0^p-V_0+ A) \sinh(X), \\
 & \quad \forall X \in [0,L_p] \\
v_0^d + B &\cosh(X-L), \quad \forall X \in [L_p,L]
\end{split}
\right.
\end{equation}

with $A$ and $B$ explicited in the supplementary material. The
accuracy of this expression can be seen on Figure
[[fig:analytics-accuracy]].

* Derivation of the mean membrane potential solution
<<sec:mean-coeff>>

Equation for $\mu_v(X)$:

\begin{equation}
\left\{
\begin{split}
& \frac{\partial^2 \mu_v}{\partial X^2} = \mu_v(X)-v_0^p \quad \forall X \in [0,L_p] \\
&\frac{\partial^2 \mu_v}{\partial X^2} = \mu_v(X)-v_0^d \quad \forall X \in [L_p,L]  \\
&\frac{\partial \mu_v}{\partial X}|_{X=0} = \gamma^p \, 
\Big( \mu_v(0) - V_0  \Big) \\
&\mu_v(X \rightarrow L_p^-) = \mu_v(X \rightarrow L_p^+) \\
&\frac{\partial \mu_v}{\partial X}_{X \rightarrow L_p^-} = \frac{\lambda^p}{\lambda^d}
\frac{\partial \mu_v}{\partial X}_{X \rightarrow L_p^+} \\
&\frac{\partial \mu_v}{\partial X}_{X=L} = 0 
\end{split}
\right.
\end{equation}

We write the solution on the form:

\begin{equation}
\left\{
\begin{split}
& \mu_v(X) = v_0^p + A \, \cosh(X) + C \, \sinh(X) \quad \forall \, X \in [0,L_p] \\
& \mu_v(X) = v_0^d + B \, \cosh(X-L) + D \, \sinh(X-L) \quad \forall \, X \in [L_pL]
\end{split}
\right.
\end{equation}


- Sealed-end boundary condition at cable end implies $D=0$

- Somatic boudary condition imply: $C = \gamma^p \, (v_0^p - V_0 + A)$

- Then v continuity imply :
    \( v_0^p + A \, \cosh(L_p) +  \gamma^p \, (v_0^p - V_0 + A) \, \sinh(L_p) = v_0^d + B \, \cosh(L_p-L) \)

- Then current conservation imply: 
    \( A \, \sinh(L_p) +  \gamma^p \, (v_0^p - V_0 + A) \, \cosh(L_p) = \frac{\lambda^p}{\lambda^d} \, B \, \sinh(L_p-L) \)

We rewrite those condition on a matrix form:

\begin{equation}
\Big(
\begin{matrix}
    \cosh(L_p)+\gamma^p \sinh(L_p) & -\cosh(L_p-L) \\
    \sinh(L_p)+\gamma^p \cosh(L_p) & -  \frac{\lambda^p}{\lambda^d} \, \sinh(L_p-L) 
\end{matrix}
\Big)
\cdot
\Big(
\begin{matrix}
    A \\
    B 
\end{matrix}
\Big) = 
\Big(
\begin{matrix}
v_0^d - v_0^p - \gamma^p \, (v_0^p-V_0) \, \sinh(L_p) \\
- \gamma^p \, (v_0^p-V_0) \, \cosh(L_p)
\end{matrix}
\Big)
\end{equation}

And we solved this equation with the =solve_linear_system_LU= method of =sympy=

The coefficients $A$ and $B$ are given by:
\begin{equation}
A=\frac{\alpha}{\beta} \qquad \qquad B=\frac{\gamma}{\delta}
\end{equation}

where:

\begin{equation}
\begin{split}
& \alpha = V_{0} \gamma^{P} \lambda^{D} \cosh{\left (L_{p} \right )}
\cosh{\left (L - L_{p} \right )} + V_{0} \gamma^{P} \lambda^{P}
\sinh{\left (L_{p} \right )} \sinh{\left (L - L_{p} \right )} \\
& \quad - \gamma^{P} \lambda^{D} v^{d}_{0} \cosh{\left (L_{p} \right )}
\cosh{\left (L - L_{p} \right )} - \gamma^{P} \lambda^{P} v^{d}_{0}
\sinh{\left (L_{p} \right )} \sinh{\left (L - L_{p} \right )} \\
& \quad - \lambda^{P} v^{d}_{0} \sinh{\left (L - L_{p} \right )}
 + \lambda^{P} v^{p}_{0} \sinh{\left (L - L_{p} \right )} \\
& \beta = \gamma^{P} \lambda^{D} \cosh{\left (L_{p} \right )}
\cosh{\left (L - L_{p} \right )} + \gamma^{P} \lambda^{P} \sinh{\left
(L_{p} \right )} \sinh{\left (L - L_{p} \right )} + \\
& \quad \lambda^{D} \sinh{\left (L_{p} \right )} \cosh{\left (L - L_{p} \right )}
 + \lambda^{P} \sinh{\left (L - L_{p} \right )} \cosh{\left (L_{p} \right
)} \\
& \gamma = \lambda^{D} \big( V_{0} \gamma^{P} + \gamma^{P} v^{d}_{0}
\cosh{\left (L_{p} \right )} - \gamma^{P} v^{d}_{0} \\
& \quad  - \gamma^{P}
v^{p}_{0} \cosh{\left (L_{p} \right )} + v^{d}_{0} \sinh{\left (L_{p}
\right )} - v^{p}_{0} \sinh{\left (L_{p} \right )} \big) \\
& \delta = \gamma^{P}
\lambda^{D} \cosh{\left (L_{p} \right )} \cosh{\left (L - L_{p} \right
)} + \gamma^{P} \lambda^{P} \sinh{\left (L_{p} \right )} \sinh{\left
(L - L_{p} \right )}  \\
& \quad + \lambda^{D} \sinh{\left (L_{p} \right )}
\cosh{\left (L - L_{p} \right )}  + \lambda^{P} \sinh{\left (L - L_{p}
\right )} \cosh{\left (L_{p} \right )}
\end{split}
\end{equation}

* Membane potential response to a synaptic event
<<sec:eq-for-var-around-mean>>

We now look for the response to \(n_{src}= \lfloor \frac{B \,
x_{src}}{l} \rfloor} \) synaptic events at position \(x_{src}\) on all
branches of the generation of \(x_src\), those events have a
conductance $g(t)/n_{src}$ and reversal potential $E_{rev}$. We make
the hypothesis that the initial condition correspond to the stationary
mean membrane potential $\mu_V(x)$. This potential will also be used
to fix the driving force at the synapse to $\mu_v(x_{src})-E_{rev}$,
this linearizes the equation and will allow an analytical
treatment. To derive the equation for the response around the mean
\(\mu_v(x)\), we rewrite Equation [[eq:model-equation]] with \(v(x, t) =
\delta v(x, t) + \mu_v(x)\), we obtain the equation for \(\delta v(x,
t)\):

#+NAME: eq:psp-equation
\begin{equation}
\left\{
\begin{split}
& \frac{1}{r_i} \frac{\partial^2 \delta v}{\partial x^2} = 
c_m \frac{\partial \delta v}{\partial t} 
+ \frac{\delta v}{r_m} (1 + r_m \, g_{e0}^p + r_m \, g_{i0}^p) \\
& \qquad - \delta(x-x_{src}) \, \big(\mu_v(x_{src})-E_{rev}\big) \, \frac{g(t)}{n_{src}},
\quad \forall x \in [0,l_p] \\
& \frac{1}{r_i} \frac{\partial^2 \delta v}{\partial x^2} = 
c_m \frac{\partial \delta v}{\partial t} 
+ \frac{\delta v}{r_m} (1 + r_m \, g_{e0}^d + r_m \, g_{i0}^d) \\
& \qquad
- \delta(x-x_{src}) \, \big(\mu_v(x_{src})-E_{rev}\big) \, \frac{g(t)}{n_{src}},
\quad   \forall x \in [l_p,l]\\
& \frac{1}{r_i} \frac{\partial \delta v}{\partial x}_{|x=0} = 
 C_M \frac{\partial \delta  v}{\partial t}_{|x=0} +  
 \frac{ \delta v(0,t)}{R_m} ( 1+ R_m G_{i0}^S) \\
&  \delta v(l_p^-,t) = \delta v(l_p^+,t) \\
& \frac{\partial \delta v}{\partial x}_{l_p^-} 
= \frac{\partial \delta v}{\partial x}_{l_p^+} \\
& \frac{\partial \delta v}{\partial x}_{x=l} = 0
\end{split}
\right.
\end{equation}

Because this synaptic event is concomitant in all branches at distance
$x_{src}$, we can use again the reduction to the equivalent cylinder
(note that the event has now a weight multiplied by $n_{src}$ so that
its conductance becomes \(g(t)\)), we obtain:

#+NAME: eq:psp-equation-reduced
\begin{equation}
\left\{
\begin{split}
& \frac{\partial^2 \delta v}{\partial X^2} =
\big( \tau_m^p + (\tau_m^d-\tau_m^p) 
\mathcal{H}(X-L_p) \big) \frac{\partial \delta v}{\partial t} + \delta v \\
& \qquad - \big(\mu_v(X_{src})-E_{rev}\big) \,  \delta(X-X_{src}) \times \\
& \qquad \qquad \frac{g(t)}{c_m} 
  \big( \frac{\tau_m^p}{\lambda^p} +
  (\frac{\tau_m^d}{\lambda^d}-\frac{\tau_m^p}{\lambda^p}) 
\mathcal{H}(X_{src}-L_p) \big) \\
& \frac{\partial \delta v}{\partial X}_{|X=0} = 
 \gamma^p \big( \tau_m^S \frac{\partial \delta  v}{\partial t}_{|X=0} +  
 \delta v(0,t) \big) \\
& \delta v(L_p^-,t) = \delta v(L_p^+,t) \\
& \frac{\partial \delta v}{\partial X}_{L_p^-} 
= \frac{\lambda^p}{\lambda^d} \, 
\frac{\partial \delta v}{\partial X}_{L_p^+} \\
& \frac{\partial \delta v}{\partial X}_{X=L} = 0
\end{split}
\right.
\end{equation}

where we have introduced the following time constants:

#+NAME: eq:time-constants
\begin{equation}
\begin{split}
 & \tau_m^D = \frac{r_m \, c_m}{1+r_m \, g_{e0}^d+r_m \, g_{i0}^d} \\
 & \tau_m^P = \frac{r_m \, c_m}{1+r_m \, g_{e0}^p+r_m \, g_{i0}^p} \\
 & \tau_m^S = \frac{R_m \, C_m}{1+R_m \, G_{i0}^S}
\end{split}
\end{equation}

Now used distribution theory (see [[citetext:Appel2008]] for a
comprehensive textbook) to translate the synaptic input into boundary
conditions at $X_{src}$, physically this corresponds to: 1) the
continuity of the membrane potential and 2) the discontinuity of the
current resulting from the synaptic input.

\begin{equation}
\left\{
\begin{split}
&  \delta v(X_{src}^-,f) = \delta v(X_{src}^+,f) \\
& \frac{\partial \delta v}{\partial X}_{X_{src}^+} 
- \frac{\partial \delta v}{\partial X}_{X_{src}^-} 
= - \big(\mu_v(X_{src})-E_{rev}\big) \times \\
& \qquad \qquad \qquad 
\big( \frac{\tau_m^p}{\lambda^p} +
  (\frac{\tau_m^d}{\lambda^d}-\frac{\tau_m^p}{\lambda^p}) 
 \mathcal{H}(X_{src}-L_p) \big) \, \frac{g(t)}{c_m} \\
\end{split}
\right.
\end{equation}

We will solve Equation [[eq:psp-equation-reduced]] by using Fourier
analysis. We take the following convention for the Fourier transform:

#+NAME: eq:fourier-convention
\begin{equation}
\hat{F}(f) = \int_\mathbb{R} F(t) \, e^{- 2 i \pi f t} \, dt
\end{equation}

We Fourier transform the set of Equations [[eq:psp-equation-reduced]], we
obtain:

#+NAME: eq:psp-equation-fourier
\begin{equation}
\left\{
\begin{split}
& \frac{\partial^2 \hat{\delta v}}{\partial X^2} =
\big( \alpha_f^p + (\alpha_f^d-\alpha_f^p) 
\mathcal{H}(X-L_p) \big)^2 \, 
\hat{\delta v}  \\
& \frac{\partial \hat{\delta v}}{\partial X}_{|X=0} = 
 \gamma_f^p \,  \hat{\delta v}(0,f) \\
&  \hat{\delta v}(X_{src}^-,f) = \hat{\delta v}(X_{src}^+,f) \\
& \frac{\partial \hat{\delta v}}{\partial X}_{X_{src}^-} 
= \frac{\partial \hat{\delta v}}{\partial X}_{X_{src}^+} 
- \big(\mu_v(X_{src})-E_{rev}\big) \times \\
& \qquad \qquad \qquad \qquad 
\big( r_f^p + (r_f^d-r_f^p) \mathcal{H}(X_{src}-L_p) \big) \, \hat{g(f)} \\
& \hat{\delta v}(L_p^-,f) = \hat{\delta v}(L_p^+,f) \\
& \frac{\partial \hat{\delta v}}{\partial X}_{L_p^-} 
= \frac{\lambda^p}{\lambda^d} \, 
\frac{\partial \hat{\delta v}}{\partial X}_{L_p^+} \\
& \frac{\partial \hat{\delta v}}{\partial X}_{X=L} = 0
\end{split}
\right.
\end{equation}

where 
\begin{equation}
\begin{split}
& \alpha_f^p = \sqrt{1+ 2 i \pi f \tau_m^p} \qquad
 r_f^p = \frac{\tau_m^p}{c_m \, \lambda^p} \\
& \alpha_f^d = \sqrt{1+ 2 i \pi f \tau_m^d} \qquad
 r_f^d = \frac{\tau_m^d}{c_m \, \lambda^d} \\
& \qquad \qquad \gamma_f^p =  \gamma^p \, (1+ 2 i \pi f \tau_m^S) \\
\end{split}
\end{equation}

This equation is solved in the supplementary material. We will use the
solution at the soma, it can be written:

\begin{equation}
\hat{\delta v}(X=0, X_{src}, f) = K_f(X_{src}) \, 
\big(\mu_v(X_{src})-E_{rev}\big) \,  \hat{g(f)} 
\end{equation}

* Derivation of the post-synaptic membrane potential event

For the PSP events we need to solve:

\begin{equation}
\left\{
\begin{split}
& \frac{\partial^2 \hat{\delta v}}{\partial X^2} =
\big( \alpha_f^p + (\alpha_f^d-\alpha_f^p) 
\mathcal{H}(X-L_p) \big)^2 \, 
\hat{\delta v}  \\
& \frac{\partial \hat{\delta v}}{\partial X}_{|X=0} = 
 \gamma_f^p \,  \hat{\delta v}(0,f) \\
&  \hat{\delta v}(X_{src}^-,f) = \hat{\delta v}(X_{src}^+,f) \\
& \frac{\partial \hat{\delta v}}{\partial X}_{X_{src}^-} 
= \frac{\partial \hat{\delta v}}{\partial X}_{X_{src}^+} 
- \big(\mu_v(X_{src})-E_{rev}\big) \, \big( r_f^p + (r_f^d-r_f^p) \mathcal{H}(X_{src}-L_p) \big) \, \hat{g(f)} \\
& \hat{\delta v}(L_p^-,f) = \hat{\delta v}(L_p^+,f) \\
& \frac{\partial \hat{\delta v}}{\partial X}_{L_p^-} 
= \frac{\lambda^p}{\lambda^d} \, 
\frac{\partial \hat{\delta v}}{\partial X}_{L_p^+} \\
& \frac{\partial \hat{\delta v}}{\partial X}_{X=L} = 0
\end{split}
\right.
\end{equation}

To obtain the solution, we need to split the solution into two cases:

**** $X_{src} \leq L_p$

Let's write the solution to this equation as the form (already
including the boundary conditions at $X=0$ and $X=L$):

\begin{equation}
\begin{split}
& \hat{\delta v}(X, X_{src}, f) = \\
&\left\{
\begin{split}
& A_f(X_{src}) \, \big ( \cosh(\alpha_f^p \, X)+\gamma^p \, \sinh(\alpha_f^p \, X) \big) \\
& \qquad \qquad \mathrm{ if: } 0 \leq X \leq X_{src} \leq L_p \leq L \\
& B_f(X_{src})\, \cosh(\alpha_f^p \, (X-L_p))+C_f(X_{src})\, \sinh(\alpha_f^p \, (X-L_p)) \\
& \qquad \qquad \mathrm{ if: } 0 \leq X_{src}  \leq X \leq L_p \leq L \\
& D_f(X_{src}) \, \cosh(\alpha_f^d \, (X-L) )  \\
& \qquad \qquad \mathrm{ if: } 0 \leq X_{src} \leq L_p  \leq X \leq L 
\end{split}
\right.
\end{split}
\end{equation}

We write the 4 conditions correspondingto the conditions in $X_{src}$
and $L_p$ to get $A_f, B_f, C_f, D_f$. On a matrix form, this gives:

\begin{equation}
\hspace{-4cm}
\footnotesize
M = 
\begin{pmatrix}
    \cosh(\alpha_f^p \, X_{src})+\gamma_f^p \sinh(\alpha_f^p \, X_{src})  
         & -\cosh(\alpha_f^p \, (X_{src}-L_p)) & -\sinh(\alpha_f^p \, (X_{src}-L_p)) & 0 \\
    \alpha_f^p \big ( \sinh(\alpha_f^p \, X_{src})+\gamma_f^p \cosh(\alpha_f^p \, X_{src})  \big)
         & - \alpha_f^p \sinh(\alpha_f^p \, (X_{src}-L_p)) & -\alpha_f^p \cosh(\alpha_f^p \, (X_{src}-L_p)) & 0 \\
    0 & 1 & 0 & - \cosh(\alpha_f^d \, (L_p-L)) \\
    0 & 0 & \alpha_f^p & -  \alpha_f^d \frac{\lambda^p}{\lambda^d} \, \sinh(\alpha_f^d \, (L_p-L))
\end{pmatrix}
\end{equation}

\begin{equation}
M \cdot
\begin{pmatrix}
    A_f \\
    B_f \\
    C_f \\
    D_f
\end{pmatrix} = 
\begin{pmatrix}
0 \\
- r_f^p I_f \\
0 \\
0
\end{pmatrix}
\end{equation}

And we will solve it with the =solve_linear_system_LU= method of
=sympy=. For the $A_f(X_{src})$ coefficient, we obtain:

\begin{equation}
A_f(X_{src}) = \frac{a^1_f(X_{src})}{a^2_f(X_{src})}
\end{equation}

with:

\begin{equation}
\begin{split}
& a^1_f(X_{src}) = I_{f} r^{P}_{f} \left(- \alpha^{D}_{f} \lambda^{P} \cosh{\left (L \alpha^{D}_{f} - L_{p} \alpha^{D}_{f} - L_{p} \alpha^{P}_{f} + X_{s} \alpha^{P}_{f} \right )}  \\
& \qquad + \alpha^{D}_{f} \lambda^{P} \cosh{\left (L \alpha^{D}_{f} - L_{p} \alpha^{D}_{f} + L_{p} \alpha^{P}_{f} - X_{s} \alpha^{P}_{f} \right )}  \\
& \qquad + \alpha^{P}_{f} \lambda^{D} \cosh{\left (L \alpha^{D}_{f} - L_{p} \alpha^{D}_{f} - L_{p} \alpha^{P}_{f} + X_{s} \alpha^{P}_{f} \right )}  \\
& \qquad + \alpha^{P}_{f} \lambda^{D} \cosh{\left (L \alpha^{D}_{f} - L_{p} \alpha^{D}_{f} + L_{p} \alpha^{P}_{f} - X_{s} \alpha^{P}_{f} \right )}\right)\\
& a^2_f(X_{src}) = \alpha^{P}_{f} \left(- \alpha^{D}_{f} \gamma^{P}_{f} \lambda^{P} \cosh{\left (- L \alpha^{D}_{f} + L_{p} \alpha^{D}_{f} + L_{p} \alpha^{P}_{f} \right )}  \\
& \qquad + \alpha^{D}_{f} \gamma^{P}_{f} \lambda^{P} \cosh{\left (L \alpha^{D}_{f} - L_{p} \alpha^{D}_{f} + L_{p} \alpha^{P}_{f} \right )} -  \\
& \qquad \alpha^{D}_{f} \lambda^{P} \sinh{\left (- L \alpha^{D}_{f} + L_{p} \alpha^{D}_{f} + L_{p} \alpha^{P}_{f} \right )}  \\
& \qquad + \alpha^{D}_{f} \lambda^{P} \sinh{\left (L \alpha^{D}_{f} - L_{p} \alpha^{D}_{f} + L_{p} \alpha^{P}_{f} \right )}  \\
& \qquad + \alpha^{P}_{f} \gamma^{P}_{f} \lambda^{D} \cosh{\left (- L \alpha^{D}_{f} + L_{p} \alpha^{D}_{f} + L_{p} \alpha^{P}_{f} \right )}  \\
& \qquad + \alpha^{P}_{f} \gamma^{P}_{f} \lambda^{D} \cosh{\left (L \alpha^{D}_{f} - L_{p} \alpha^{D}_{f} + L_{p} \alpha^{P}_{f} \right )}  \\
& \qquad + \alpha^{P}_{f} \lambda^{D} \sinh{\left (- L \alpha^{D}_{f} + L_{p} \alpha^{D}_{f} + L_{p} \alpha^{P}_{f} \right )}  \\
& \qquad + \alpha^{P}_{f} \lambda^{D} \sinh{\left (L \alpha^{D}_{f} - L_{p} \alpha^{D}_{f} + L_{p} \alpha^{P}_{f} \right )}\right)\\
\end{split}
\end{equation}

**** $ L_p \leq X_{src}$


Let's write the solution to this equation as the form (already
including the boundary conditions at $X=0$ and $X=L$:

\begin{equation}
\begin{split}
& \hat{\delta v}(X, X_{src}, f) = \\
&\left\{
\begin{split}
& E_f(X_{src}) \, \big ( \cosh(\alpha_f^p \, X)+\gamma^p \, \sinh(\alpha_f^p \, X) \big) \\
& \qquad \qquad \mathrm{ if: } 0 \leq X \leq L_p \leq X_{src} \leq L \\
& F_f(X_{src})\, \cosh(\alpha_f^d \, (X-L_p))+G_f(X_{src})\, \sinh(\alpha_f^d \, (X-L_p)) \\
& \qquad \qquad \mathrm{ if: } 0  \leq L_p  \leq X \leq X_{src} \leq L \\
& H_f(X_{src}) \, \cosh(\alpha_f^d \, (X-L) )  \\
& \qquad \qquad \mathrm{ if: } 0  \leq L_p \leq X_{src}  \leq X \leq L 
\end{split}
\right.
\end{split}
\end{equation}

We write the 4 conditions correspondingto the conditions in $X_{src}$
and $L_p$ to get $A_f, B_f, C_f, D_f$. On a matrix form, this gives:

We rewrite this condition on a matrix form:

\begin{equation}
\hspace{-4cm}
\footnotesize
M_2 = 
\begin{pmatrix}
    \cosh(\alpha_f^p \, L_p)+\gamma_f^p \sinh(\alpha_f^p \, L_p) & -1 & 0 &0 & 0 \\
    \alpha_f^p \big ( \sinh(\alpha_f^p \, L_p)+\gamma_f^p \cosh(\alpha_f^p \, L_p)  \big) 
         & 0 & -  \alpha_f^d \frac{\lambda^p}{\lambda^d} & 0 \\
    0 & \cosh(\alpha_f^d \, (X_{src}-L_p)) & \sinh(\alpha_f^d \, (X_{src}-L_p)) & - \cosh(\alpha_f^d \, (X_{src}-L))\\
    0 & \alpha_f^d \, \sinh(\alpha_f^d \, (X_{src}-L_p)) & \alpha_f^d \, \cosh(\alpha_f^d \, (X_{src}-L_p))
         & - \alpha_f^d \, \sinh(\alpha_f^d \, (X_{src}-L))\\
\end{pmatrix}
\end{equation}

\begin{equation}
M \cdot
\begin{pmatrix}
    E_f \\
    F_f \\
    G_f \\
    H_f
\end{pmatrix} = 
\begin{pmatrix}
0 \\
0 \\
0 \\
- r_f^d I_f
\end{pmatrix}
\end{equation}

And we will solve it with the =solve_linear_system_LU= method of
=sympy=. For the $E_f(X_{src})$ coefficient, we obtain:

\begin{equation}
E_f(X_{src}) = \frac{e^1_f(X_{src})}{e^2_f(X_{src})}
\end{equation}

with:

\begin{equation}
\begin{split}
& e^1_f(X_{src}) = 2 I_{f} \lambda^{P} r^{D}_{f} \cosh{\left (\alpha^{D}_{f} \left(L - X_{s}\right) \right )} \\
& e^2_f(X_{src}) = - \alpha^{D}_{f} \gamma^{P}_{f} \lambda^{P} \cosh{\left (- L \alpha^{D}_{f} + L_{p} \alpha^{D}_{f} + L_{p} \alpha^{P}_{f} \right )} \\
& \qquad + \alpha^{D}_{f} \gamma^{P}_{f} \lambda^{P} \cosh{\left (L \alpha^{D}_{f} - L_{p} \alpha^{D}_{f} + L_{p} \alpha^{P}_{f} \right )}  \\
& \qquad- \alpha^{D}_{f} \lambda^{P} \sinh{\left (- L \alpha^{D}_{f} + L_{p} \alpha^{D}_{f} + L_{p} \alpha^{P}_{f} \right )}  \\
& \qquad+ \alpha^{D}_{f} \lambda^{P} \sinh{\left (L \alpha^{D}_{f} - L_{p} \alpha^{D}_{f} + L_{p} \alpha^{P}_{f} \right )}  \\
& \qquad+ \alpha^{P}_{f} \gamma^{P}_{f} \lambda^{D} \cosh{\left (- L \alpha^{D}_{f} + L_{p} \alpha^{D}_{f} + L_{p} \alpha^{P}_{f} \right )}  \\
& \qquad+ \alpha^{P}_{f} \gamma^{P}_{f} \lambda^{D} \cosh{\left (L \alpha^{D}_{f} - L_{p} \alpha^{D}_{f} + L_{p} \alpha^{P}_{f} \right )}  \\
& \qquad+ \alpha^{P}_{f} \lambda^{D} \sinh{\left (- L \alpha^{D}_{f} + L_{p} \alpha^{D}_{f} + L_{p} \alpha^{P}_{f} \right )}  \\
& \qquad+ \alpha^{P}_{f} \lambda^{D} \sinh{\left (L \alpha^{D}_{f} - L_{p} \alpha^{D}_{f} + L_{p} \alpha^{P}_{f} \right )}
\end{split}
\end{equation}


**** PSP at the soma

The main text writes a solution for the PSP at soma of the form:

\begin{equation}
\hat{\delta v}(X=0, X_{src}, f) = K_f(X_{src}) \, 
\big(\mu_v(X_{src})-E_{rev}\big) \,  \hat{g(f)} 
\end{equation}

The correspondance with the previous calculus is to take a unitary
current \(I_f=1\) and \( K_f(X_{src}) \) given by:

\begin{equation}
K_f(X_{src}) = 
\left\{
\begin{split}
& A_f(X_{src}) \forall X_{src} \in [0,L_p] \\
& E_f(X_{src}) \forall X_{src} \in [L_p, L]
\end{split}
\right.
\end{equation}

* Deriving the fluctuations properties

From shotnoise theory [[cite:Daley2007]] (see also
[[citetext:ElBoustani2009a]] for an application similar to ours), we can
obtain the power spectral density of the V_m fluctuations \( P_V(f) \)
as a response to the stimulation Equation [[eq:fluct-eq]]:

From point process theory, this can be seen as two nested point
processes. The first point process follows a Poisson process which
determines the cluster positions and the second one determines
randomly the position of kz1 points within each cluster according to
an arbitrary density probability function. The correspondance between
both representations is straightforward and the power spectrum density
can be computed analytically with the Neyman-Scott equation
[23,24,51]

#+NAME: eq:vm-pwd
\begin{equation}
\begin{split}
 P_V(f)  = & \sum_{syn} \nu_{syn} \, \| \hat{\mathrm{PSP}}(f) \|^2 \\
 & = 2 \nu_{in} \, \frac{Q_I^2 \, \tau_S^2 / \mu_G^2 }{
 (1+4 \pi^2 f^2 \tau_S^2)(1+4 \pi^2 f^2 \tau_m^2)}
\end{split}
\end{equation}

#+NAME: eq:Tv-def-with-pwd
\begin{equation}
  \tau_V = \frac{1}{2} \, \big( \frac{\int_\mathbb{R} P_V(f) \, d f}{ P_V(0) } \big)^{-1}
\end{equation}

#+NAME: eq:var-expr
\begin{equation}
  \sigma_V^2 = \int_\mathbb{R} P_V(f) \, df
\end{equation}

* Variability in the fluctuations properties introduced by the different morphologies

Here we 

* Residual correlations after accounting for the excitability effects
* References
\bibliography{tex/biblio}
