#+TITLE: Response to reviewers
#+AUTHOR: Y. Zerlaut & A. Destexhe
#+INCLUDE: ~/work/common_libraries/org-mode/report_template.org

* Reviewer #1

Unfortunately, it is very difficult to grasp the essence and even more
the details of the study.

1) Main statement; presentation. It starts with the title that claims
   that claims that “Heterogeneous Firing Responses Predict Diverse
   Couplings to Presynaptic Activity in mice Layer V Pyramidal
   Neurons”. The title refers to the phenomenology in Figure 5 showing
   that the output frequency goes up or down for different cells as a
   function of “increasing presynaptic quantity”, as the x-axis in
   that figure is label. But not clear how strong the increase is at
   the corresponding position, nor what of the presynaptic quantity
   is. For us (the writer and two other group members) it was neither
   possible to figure it out from the caption nor the text.

\bfseries

We agree with the reviewer that this way to represent data might not
be straightforward. We improved the legend of Figure 4 to facilitate
the comprehension.


The difficulty here is that, to emulate the comodulations that
characterize neocortical dynamics (e.g. inhibition follows
excitation), one has to make variables co-vary at the same time, so
one can not represent the data as a function of a single variable.


Nonetheless, what we want to represent...the
difficulty here, is that the x-axis (increasing one synaptic quantity,
e.g. release probability of proximal synapses) corresponds to a
comodulation of

\textnormal

2) Main statement unclear. Unfortunately, it does not become clear
   what one has to understand of the “Diverse Couplings to the
   Presynaptic Activity” as expressed in the title. In the abstract it
   is stated: “We indeed found such a heterogeneous response, but
   trivially, the only significant contribution to the various firing
   response was the different levels of cellular excitability.” We
   guess that the “trivially” refers to the fact that only the
   cellular excitability has been modulated in the model. But then we
   don’t understand “A notable exception appeared for proximal
   activity: increasing proximal activity could either promote firing
   response in some cells or suppress it in some other cells whatever
   their individual excitability.” We conclude that there is still
   more than the individual excitability that determines the firing
   behavior, but this seems to contradict the previous statement.

\bfseries

We skjdf

\textnormal

3) Main statement; missing analysis. It is suggested that the
   heterogeneity would arise from sodium channels, but the paper is
   missing a joint presentation of experimental and modeling data
   showing some fit. Neither could we find a mathematical argument why
   the different phenomenological behavior shown in the cited Fig. 5
   should arise. It would be helpful to underscore the main statement
   by a simplified mathematical formulation in the main text. For
   instance, a simplified formula that gives the output firing rate as
   a function of the input variables would be helpful, including the
   dependencies on the sodium channel density. This sodium channel
   density is claimed to make the difference between the cell types
   according to the abstract: “various levels of density of sodium
   channels and sodium inactivation will control the response of
   individual neurons to proximally targeting presynaptic activity.”
   Again, we could not find a state-of-the-art explanation why this
   statement is true.

\bfseries

The sharpness of the sodium activation curve controls the ability of
neocortical neurons to respond to fast fluctuating input. So if for
some neurons this

Unfortunately, there is, to the best of our knowledge, no closed-form
solution for the (only numerical solutions of the Fokker-Planck
equation)

We skjdf

\textnormal


4) No dendritic nonlinearities. One main characteristics of L5
   pyramidal neurons is the calcium spike in the apical tree, and more
   generally the various types of dendritic spikes. Non of them is
   considered in the model, and one conjectures that the various
   response properties in the experimental data arise from these
   various dendritic nonlinearities. Describing the firing properties
   of pyramidal neurons as a function of proximal and distal activity
   should take account of these dendritic nonlinearities. Otherwise,
   in fact, the statements cannot be compelling.

5) Data extraction. It is not clear how the 4 cells have been selected
   out of the 27 cells. The 4 cells represent 4 cell types. How are
   these cell types specified? The paper does not give an answer on
   that.

6) Figure 2 has two panels A & B, but the caption describes panels A –
   E. Apart from that, the fit of the numerical simulations and the
   analytical estimate in B for sigma_V is biased. No argument is
   given why this bias is there.

7) The central claim is that distal and proximal inputs differently
   affects the output firing rates. Beside the fact that this
   statement by itself is trivial, we wondered why the closer 87.5% of
   the dendritic branch is declared as “proximal” and the furthest
   12.5% as the “distal” part. Is the result dependent on this choice,
   or could one have also chosen the closer 12.5% as “proximal” only?

\bfseries

We reproduced in Figure the analysis with the convention "proximal
only as the closest 12.5%"

This is indeed an important question. The main motivation behind the
arbitrary choice for the separation is related to the electrotonic
distance profiles in (i) real layer V pyramidal cells and (ii) the
proposed reduced geometry. 

\textnormal

* Reviewer #2

 This manuscript shows a nice mixture of experiment and theory. The
 latter is based upon sensible use of the cable modelling framework of
 Rall combined with stochastic models of synaptic input (admittedly of
 a particular type but definitely fit for purpose). Unfortunately some
 of the work (for the firing response function) is buried in
 supplementary material - and this has not been made available to me
 (S1). It would be especially informative to hear more about the
 author's perspective on how synchrony controls rate. Nonetheless
 given the quality and novelty of the main manuscript I suggest to put
 this issue aside. 

** Major concern

My only major concern with the paper is on the emphasis of a
theoretical framework without citing other relevant work in the
area. Essentially I am surprised not to see the mention of the
technique(s) for constructing the Green's function of an arbitrary
branched passive dendritic tree. The paper focuses on Rall equivalent
cylinders for simplicity, yet the methodology presented would seem
easily extended using the work of Abbott:

L. F. Abbott, E. Fahri, and S. Gutmann, “The path integral for
dendritic trees,” Biological Cybernetics, vol. 66, pp. 49–60, 1991.

L. F. Abbott, “Simple diagrammatic rules for solving dendritic cable
problems,” Physica A, vol. 185, no. 343-356, 1992.

B.J.Cao and L.F.Abbott,“New computational method for cable theory
problems,”Biophysical Journal, vol. 64, pp. 303–313, 1993.

The extension of the above to include a distinguished soma model can
be found in

S Coombes, Y Timofeeva, C-M Svensson, G J Lord, K Josic, S J Cox and C
M Colbert 2007 Branching Dendrites with Resonant Membrane: A
"sum-over-trips" approach, Biological Cybernetics, Vol 97, 137-149

and Paul Bressloff has done a lot of work on dendrites that appears
relevant, some of which is summarised in:

P C Bressloff and S Coombes 1997 Physics of the extended neuron,
International Journal of Modern Physics B, Vol 11, No 20, 2343-2392

The following may also be of interest (though not necessarily for this
work) - where simple active soma models are coupled to passive
dendrites

Paul C. Bressloff, Dynamics of a compartmental model
integrate-and-fire neuron with somatic potential reset, Physica D:
Nonlinear Phenomena, Volume 80, Issue 4, 1995, Pages 399-412

C-M Svensson and S Coombes 2009 Mode locking in a spatially extended
neuron model: active soma and compartmental tree, International
Journal of Bifurcation and Chaos, Vol 19, 2597-2607

M. A. Schwemmer and T.J. Lewis (2012) Bistability in a leaky
integrate-and-fire Neuron with a passive dendrite SIAM
J. Appl. Dyn. Syst. 11(1): 507-530

\bfseries

Indeed, our 

We thank the reviewer

\textnormal

** Minor points

Spurious "s" in the sec "A simplified morphological model" - sWe arbitrarily ...
Where is excitability < V_thre^eff >_D defined?

* Reviewer #3

The key claim of this work is that recently identified L5 PCs firing
rate properties indicate how these cells couple to presynaptic
activity patterns (proximal, distal,...). The claim is based on i)
recently identified firing response functions (previous work of the
authors), ii) a theoretical model for passive dendritic integration
that is an extension of the single compartment model of Kuhn et al. [[19]]
to a passive tree with cable theory, and iii) an identification of the
passive tree of L5 PCs by fitting the input impedance at the soma to
experimental data.

The topic is of importance and the theoretical part is novel, very
appealing in itself and rigorous, but inadequate to support the key
claim of the paper (see paper title).

This is because ...

** CONS

 - *A*: (part ii) For L5 PCs it is highly questionable if dendritic
   integration can be understood without (or separated from) active
   dendritic properties given the known experimental facts and huge
   literature, e.g. about the compartmentalization of dendritic
   function, dendritic spikes, and changed response properties due to
   ion channel blockers.
   
   In my opinion, the model for the L5 PCs based on a passive tree
   will almost surely fail to describe the real dendritic integration
   properties of the cells in the fluctuation driven regime. In any
   case, see the first point in additional work below.


- *B*: (part iii) Even the description of the passive dendritic
  integration properties of the cell seems to be questionable (maybe
  because of the constraints to symmetrical trees). That this doesn't
  work out properly seems to be reflected in the morphologies obtained
  in the paper: Is the required variation of the tree length from
  about 400 um to 900 um (current Fig 3C and Fig. S1) for PCs
  plausible? Please provide references. L5 PCs with their long apical
  dendrites etc. are the worst case scenario for the symmetry
  constraints for the tree.


** PROS

The theoretical work is still significant for other cell types that
work in a more linear regime, e.g. L2/3 PCs, and have morphologies
that match the theoretical constraints..


** Additional work required:

- The authors should provide evidence that active dendritic
  integration doesn't change the key claim, or, apply the model to a
  more appropriate cell type.

- Because the morphology of the tree of the model is very constraint
  and only a very rough estimate its necessary to assess the influence
  of this approximation on dendritic integration: A systematic
  analysis of the impact of the morphology of the tree (7 variables)
  on the response properties of interest at the soma is missing (This
  allows also a generalization of the results to other cell types. Now
  only Fig S2 gives a hint about variability).

- There's no reference to any other model than Kuhn et al., on which
  the approach is based. Relate the model to recent work on the
  effects of passive dendritic tree properties of neuron on firing
  dynamics (e.g. [[1]] or other model reduction techniques (a huge field,
  e.g. [[2]]).

[[1]] Saparov, A., & Schwemmer, M. A. (2015). Effects of passive dendritic
tree properties on the firing dynamics of a leaky-integrate-and-fire
neuron. Mathematical biosciences, 269, 61-75.  

[[2]] Hedrick, K. R., & Cox, S. J. (2013). Structure-preserving model
reduction of passive and quasi-active neurons. Journal of
computational neuroscience, 34(1), 1-26.


The paper is well organized, easy to read, simple to follow and
clearly written. However, there are too many typos and word
repetitions to list them all ("sWe" p.3, "show deviations from the
deviations" p.4, " vary the size of the size" p.4, "does not goes",
p.6, "the firing increase show", p.7 ...) and the Figure numbers were
incorrect (Fig.22b, p.4) or mixed up (Fig. 2 and 3).


Minor:

- Fig. 3: The color code seems to be inconsistent: Panel A shows cells
  with Rm above 600 MOhm, but the bottom panel in Fig 3C shows that
  such cells are not present.

- Fig 3C: The lines in the three top panels could be drawn with the
  color code (color changes within a line) as used in panel A and B.

- Fig 3AB: Please comment on the inconsistency between data and model
  for > 100 Hz. There seems to be a flip in vertical order.

Section: "An analytical approximation ...":

- The claim "the analytical estimate could therefore be seen as an accurate estimate, module a shift in the synchrony (~0.2 increase in synchrony corrects for the ~1 mV shift in sigma)" should verified:
1) Results for synchrony = 0.2 should be shown in the right most column of panels in Fig 2B, and
2) results for synchrony = 0.2 should be shown for the other columns of panels in Fig 2B, where the other parameters are varied.

Section: "Biophysical origin ..."

- The characteristics of the firing response function are not properly introduced. Please add this.

- It can be hardly claimed that Fig. 6A is approximately a log normal distribution.

Methods section:

- Not all variables are properly defined, e.g. Qe, Qi, lp.

- "it constitutes an extension of the approach proposed in Kuhn et al. \[19\]": Please, state what extension.

- "Fitting passive properties": Are the solutions unique or are there many different trees with similar fit performance that result in different couplings to presynaptic activity?
 
